version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - FLASK_DEBUG=1  # Nueva variable de entorno
    volumes:
      - .:/code  # Monta el directorio de trabajo del anfitrión como un bind mount en /code del contenedor
    restart: on-failure

  redis:
    image: redis:alpine
