apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-web
  template:
    metadata:
      labels:
        app: front-web
    spec:
      containers:
      - name: web
        image: edersampayo/as-laboratorio-8-web
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_DEBUG
          value: "1"
